// Auto-generated by parse_paragon_inbox.py — June 30, 2026
window.MARKET_DATA = {
  "generated": "June 30, 2026",
  "rates": {
    "rate30": 6.49,
    "change30": 0.02,
    "rate15": 5.84,
    "change15": 0.03
  },
  "rapidCity": {
    "zhvi": 365969,
    "zhviChange": -0.2,
    "salePrice": 337333,
    "salePriceChange": 0.9,
    "inventory": 353,
    "inventoryChange": 21,
    "newListings": 136,
    "pctAbove": 15
  },
  "trend": [
    {
      "month": "Dec '25",
      "value": 364014
    },
    {
      "month": "Jan '26",
      "value": 365424
    },
    {
      "month": "Feb '26",
      "value": 366603
    },
    {
      "month": "Mar '26",
      "value": 366986
    },
    {
      "month": "Apr '26",
      "value": 366654
    },
    {
      "month": "May '26",
      "value": 365969
    }
  ],
  "tiers": [
    {
      "label": "1 BR  (~$100K\u2013$250K)",
      "value": 196430,
      "change": -0.5
    },
    {
      "label": "2 BR  (~$250K\u2013$320K)",
      "value": 279961,
      "change": -0.3
    },
    {
      "label": "3 BR  (~$320K\u2013$400K)",
      "value": 351739,
      "change": -0.2
    },
    {
      "label": "4 BR  (~$400K\u2013$500K)",
      "value": 417338,
      "change": -0.1
    },
    {
      "label": "5 BR+ (~$500K+)",
      "value": 556517,
      "change": -0.0
    }
  ],
  "cities": [
    {
      "name": "Rapid City",
      "zhvi": 365969,
      "zhviChange": -0.2,
      "inventory": 353,
      "inventoryChange": 21,
      "newListings": 136
    },
    {
      "name": "Spearfish",
      "zhvi": 456377,
      "zhviChange": -0.5,
      "inventory": 80,
      "inventoryChange": 5,
      "newListings": 25
    },
    {
      "name": "Sturgis",
      "zhvi": 377164,
      "zhviChange": -0.4,
      "inventory": 39,
      "inventoryChange": 5,
      "newListings": 14
    },
    {
      "name": "Hot Springs",
      "zhvi": 346265,
      "zhviChange": -0.5,
      "inventory": 75,
      "inventoryChange": 8,
      "newListings": 19
    },
    {
      "name": "Box Elder",
      "zhvi": 368804,
      "zhviChange": -0.3,
      "inventory": 35,
      "inventoryChange": 3,
      "newListings": 14
    },
    {
      "name": "Hermosa",
      "zhvi": 541461,
      "zhviChange": -0.4,
      "inventory": 6,
      "inventoryChange": 2,
      "newListings": null
    },
    {
      "name": "Custer",
      "zhvi": 488776,
      "zhviChange": -0.0,
      "inventory": 32,
      "inventoryChange": 3,
      "newListings": 10
    },
    {
      "name": "Piedmont",
      "zhvi": null,
      "zhviChange": null,
      "inventory": 23,
      "inventoryChange": 4,
      "newListings": 10
    }
  ],
  "mlsDetail": {
    "categories": [
      "Residential Resale (Single Family)",
      "Commercial \u2014 Multi-Family",
      "Commercial \u2014 Industrial",
      "Commercial \u2014 General Commercial"
    ],
    "priceBands": [
      "$100K\u2013$350K",
      "$350K\u2013$500K",
      "$500K\u2013$800K",
      "$800K\u2013$1.0M",
      "$1.0M+"
    ],
    "statuses": [
      "Active",
      "Under Contract",
      "Sold"
    ],
    "data": {
      "Residential Resale (Single Family)": {
        "$100K\u2013$350K": {
          "Active": 22,
          "Under Contract": null,
          "Sold": null
        },
        "$350K\u2013$500K": {
          "Active": 31,
          "Under Contract": null,
          "Sold": null
        },
        "$500K\u2013$800K": {
          "Active": 6,
          "Under Contract": null,
          "Sold": null
        },
        "$800K\u2013$1.0M": {
          "Active": 3,
          "Under Contract": null,
          "Sold": null
        },
        "$1.0M+": {
          "Active": 3,
          "Under Contract": null,
          "Sold": null
        }
      },
      "Commercial \u2014 Multi-Family": {
        "$100K\u2013$350K": {
          "Active": null,
          "Under Contract": null,
          "Sold": null
        },
        "$350K\u2013$500K": {
          "Active": null,
          "Under Contract": null,
          "Sold": null
        },
        "$500K\u2013$800K": {
          "Active": null,
          "Under Contract": null,
          "Sold": null
        },
        "$800K\u2013$1.0M": {
          "Active": null,
          "Under Contract": null,
          "Sold": null
        },
        "$1.0M+": {
          "Active": null,
          "Under Contract": null,
          "Sold": null
        }
      },
      "Commercial \u2014 Industrial": {
        "$100K\u2013$350K": {
          "Active": null,
          "Under Contract": null,
          "Sold": null
        },
        "$350K\u2013$500K": {
          "Active": null,
          "Under Contract": null,
          "Sold": null
        },
        "$500K\u2013$800K": {
          "Active": null,
          "Under Contract": null,
          "Sold": null
        },
        "$800K\u2013$1.0M": {
          "Active": null,
          "Under Contract": null,
          "Sold": null
        },
        "$1.0M+": {
          "Active": null,
          "Under Contract": null,
          "Sold": null
        }
      },
      "Commercial \u2014 General Commercial": {
        "$100K\u2013$350K": {
          "Active": null,
          "Under Contract": null,
          "Sold": null
        },
        "$350K\u2013$500K": {
          "Active": null,
          "Under Contract": null,
          "Sold": null
        },
        "$500K\u2013$800K": {
          "Active": null,
          "Under Contract": null,
          "Sold": null
        },
        "$800K\u2013$1.0M": {
          "Active": null,
          "Under Contract": null,
          "Sold": null
        },
        "$1.0M+": {
          "Active": 2,
          "Under Contract": null,
          "Sold": null
        }
      }
    }
  }
};
