// Auto-generated by mls_report.py — July 24, 2026
window.MARKET_DATA = {
  "generated": "July 24, 2026",
  "rates": {
    "rate30": 6.58,
    "change30": 0.03,
    "rate15": 5.96,
    "change15": 0.03
  },
  "rapidCity": {
    "zhvi": 367620,
    "zhviChange": -0.2,
    "salePrice": 352750,
    "salePriceChange": 5.0,
    "inventory": 365,
    "inventoryChange": 12,
    "newListings": 134,
    "pctAbove": 15
  },
  "trend": [
    {
      "month": "Jan '26",
      "value": 367774
    },
    {
      "month": "Feb '26",
      "value": 368961
    },
    {
      "month": "Mar '26",
      "value": 369347
    },
    {
      "month": "Apr '26",
      "value": 369012
    },
    {
      "month": "May '26",
      "value": 368324
    },
    {
      "month": "Jun '26",
      "value": 367620
    }
  ],
  "tiers": [
    {
      "label": "1 BR  (~$100K\u2013$250K)",
      "value": 198379,
      "change": -0.1
    },
    {
      "label": "2 BR  (~$250K\u2013$320K)",
      "value": 280326,
      "change": -0.3
    },
    {
      "label": "3 BR  (~$320K\u2013$400K)",
      "value": 353112,
      "change": -0.2
    },
    {
      "label": "4 BR  (~$400K\u2013$500K)",
      "value": 420002,
      "change": -0.1
    },
    {
      "label": "5 BR+ (~$500K+)",
      "value": 563596,
      "change": 0.1
    }
  ],
  "cities": [
    {
      "name": "Rapid City",
      "zhvi": 367620,
      "zhviChange": -0.2,
      "inventory": 365,
      "inventoryChange": 12,
      "newListings": 134
    },
    {
      "name": "Spearfish",
      "zhvi": 461765,
      "zhviChange": -0.4,
      "inventory": 86,
      "inventoryChange": 6,
      "newListings": 26
    },
    {
      "name": "Sturgis",
      "zhvi": 378808,
      "zhviChange": -0.3,
      "inventory": 47,
      "inventoryChange": 8,
      "newListings": 19
    },
    {
      "name": "Hot Springs",
      "zhvi": 343395,
      "zhviChange": -0.8,
      "inventory": 81,
      "inventoryChange": 6,
      "newListings": 19
    },
    {
      "name": "Box Elder",
      "zhvi": 370374,
      "zhviChange": -0.3,
      "inventory": 38,
      "inventoryChange": 3,
      "newListings": 13
    },
    {
      "name": "Hermosa",
      "zhvi": 544212,
      "zhviChange": -0.6,
      "inventory": 7,
      "inventoryChange": 1,
      "newListings": null
    },
    {
      "name": "Custer",
      "zhvi": 489701,
      "zhviChange": -0.3,
      "inventory": 37,
      "inventoryChange": 5,
      "newListings": 12
    },
    {
      "name": "Piedmont",
      "zhvi": null,
      "zhviChange": null,
      "inventory": 21,
      "inventoryChange": -2,
      "newListings": null
    }
  ],
  "mlsDetail": {
    "categories": [
      "Residential Resale (Single Family)",
      "Commercial \u2014 Multi-Family",
      "Commercial \u2014 Industrial",
      "Commercial \u2014 General Commercial"
    ],
    "priceBands": [
      "$100K\u2013$350K",
      "$350K\u2013$500K",
      "$500K\u2013$800K",
      "$800K\u2013$1.0M",
      "$1.0M+"
    ],
    "statuses": [
      "Active",
      "Under Contract",
      "Sold"
    ],
    "data": null
  }
};
