// Auto-generated by mls_report.py — August 28, 2026
window.MARKET_DATA = {
  "generated": "August 28, 2026",
  "rates": {
    "rate30": 6.66,
    "change30": 0.01,
    "rate15": 5.98,
    "change15": 0.03
  },
  "rapidCity": {
    "zhvi": 367120,
    "zhviChange": -0.1,
    "salePrice": 366933,
    "salePriceChange": 4.0,
    "inventory": 386,
    "inventoryChange": 20,
    "newListings": 136,
    "pctAbove": 16
  },
  "trend": [
    {
      "month": "Feb '26",
      "value": 368652
    },
    {
      "month": "Mar '26",
      "value": 369038
    },
    {
      "month": "Apr '26",
      "value": 368704
    },
    {
      "month": "May '26",
      "value": 368016
    },
    {
      "month": "Jun '26",
      "value": 367313
    },
    {
      "month": "Jul '26",
      "value": 367120
    }
  ],
  "tiers": [
    {
      "label": "1 BR  (~$100K\u2013$250K)",
      "value": 197873,
      "change": 0.2
    },
    {
      "label": "2 BR  (~$250K\u2013$320K)",
      "value": 282531,
      "change": -0.1
    },
    {
      "label": "3 BR  (~$320K\u2013$400K)",
      "value": 353372,
      "change": -0.0
    },
    {
      "label": "4 BR  (~$400K\u2013$500K)",
      "value": 419360,
      "change": -0.0
    },
    {
      "label": "5 BR+ (~$500K+)",
      "value": 561886,
      "change": 0.1
    }
  ],
  "cities": [
    {
      "name": "Rapid City",
      "zhvi": 367120,
      "zhviChange": -0.1,
      "inventory": 386,
      "inventoryChange": 20,
      "newListings": 136
    },
    {
      "name": "Spearfish",
      "zhvi": 461084,
      "zhviChange": -0.1,
      "inventory": 92,
      "inventoryChange": 6,
      "newListings": 25
    },
    {
      "name": "Sturgis",
      "zhvi": 377712,
      "zhviChange": -0.4,
      "inventory": 53,
      "inventoryChange": 6,
      "newListings": 19
    },
    {
      "name": "Hot Springs",
      "zhvi": 340420,
      "zhviChange": -1.4,
      "inventory": 83,
      "inventoryChange": 2,
      "newListings": 13
    },
    {
      "name": "Box Elder",
      "zhvi": 370689,
      "zhviChange": -0.1,
      "inventory": 43,
      "inventoryChange": 5,
      "newListings": 14
    },
    {
      "name": "Hermosa",
      "zhvi": 542042,
      "zhviChange": -0.4,
      "inventory": 8,
      "inventoryChange": 1,
      "newListings": null
    },
    {
      "name": "Custer",
      "zhvi": 484375,
      "zhviChange": -0.3,
      "inventory": 41,
      "inventoryChange": 4,
      "newListings": 11
    },
    {
      "name": "Piedmont",
      "zhvi": null,
      "zhviChange": null,
      "inventory": 22,
      "inventoryChange": null,
      "newListings": 5
    }
  ],
  "mlsDetail": {
    "categories": [
      "Residential Resale (Single Family)",
      "Commercial \u2014 Multi-Family",
      "Commercial \u2014 Industrial",
      "Commercial \u2014 General Commercial"
    ],
    "priceBands": [
      "$100K\u2013$350K",
      "$350K\u2013$500K",
      "$500K\u2013$800K",
      "$800K\u2013$1.0M",
      "$1.0M+"
    ],
    "statuses": [
      "Active",
      "Under Contract",
      "Sold"
    ],
    "data": null
  }
};
