#!/usr/bin/env python3
"""
MLS Detail Manual Entry — Kevin Andreson / Keller Williams Black Hills
Run this after checking Paragon to enter Active / Under Contract / Sold counts.
It updates the MLS detail grid in the dashboard (js/market-data.js).

Usage:
  python3 update_mls_detail.py

Press Enter to skip a cell (leaves it as —).
Press Ctrl+C at any time to cancel without saving.
"""
import json, os, re, sys
from datetime import datetime

MARKET_DATA_JS = os.path.join(os.path.dirname(__file__), '..', '..', 'js', 'market-data.js')

CATEGORIES = [
    "Residential Resale (Single Family)",
    "Commercial — Multi-Family",
    "Commercial — Industrial",
    "Commercial — General Commercial",
]

PRICE_BANDS = [
    "$100K–$350K",
    "$350K–$500K",
    "$500K–$800K",
    "$800K–$1.0M",
    "$1.0M+",
]

STATUSES = ["Active", "Under Contract", "Sold"]


def load_current():
    with open(MARKET_DATA_JS, 'r') as f:
        content = f.read()
    match = re.search(r'window\.MARKET_DATA\s*=\s*(\{[\s\S]*\});', content)
    if not match:
        print("ERROR: Could not parse market-data.js")
        sys.exit(1)
    return json.loads(match.group(1)), content


def save(data, original_content):
    new_json = json.dumps(data, indent=2)
    header = f"// Auto-generated by mls_report.py — {datetime.now().strftime('%B %d, %Y')}\n"
    new_content = header + f"window.MARKET_DATA = {new_json};\n"
    with open(MARKET_DATA_JS, 'w') as f:
        f.write(new_content)
    print(f"\n✓ Saved to {os.path.abspath(MARKET_DATA_JS)}")


def prompt_int(label, current):
    cur_str = str(current) if current is not None else "—"
    try:
        raw = input(f"  {label} [{cur_str}]: ").strip()
    except EOFError:
        return current
    if not raw:
        return current
    try:
        return int(raw)
    except ValueError:
        print("  (invalid — keeping current)")
        return current


def main():
    print("\nMLS Detail Manual Entry")
    print("=" * 52)
    print("Pull numbers from Paragon for each category.")
    print("Press Enter to keep the current value. Ctrl+C to cancel.\n")

    data, content = load_current()

    current_detail = data.get("mlsDetail", {}).get("data") or {}
    if isinstance(current_detail, dict):
        detail = current_detail
    else:
        detail = {}

    for cat in CATEGORIES:
        print(f"\n── {cat} ──────────────────────────────")
        if cat not in detail:
            detail[cat] = {}
        for band in PRICE_BANDS:
            print(f"\n  {band}")
            if band not in detail[cat]:
                detail[cat][band] = {}
            for status in STATUSES:
                cur = detail[cat][band].get(status)
                detail[cat][band][status] = prompt_int(status, cur)

    data["mlsDetail"]["data"] = detail
    data["generated"] = datetime.now().strftime("%B %d, %Y")

    print("\n" + "=" * 52)
    confirm = input("Save and update dashboard? [Y/n]: ").strip().lower()
    if confirm in ("", "y", "yes"):
        save(data, content)
        print("\nDone. Open index.html or run git push to publish.\n")
    else:
        print("\nCancelled — nothing saved.\n")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\nCancelled.\n")
