#!/usr/bin/env python3
"""
Development News Fetcher — Kevin Andreson / Keller Williams Black Hills
Scrapes the same planning/zoning sources as the Zoning Monitor and asks
Claude to reformat findings into 3-5 newsletter-ready bullet points.
Writes output to js/dev-news.js so the newsletter web builder auto-loads it.

Run manually or add to the Monday market report cron:
  python3 fetch_dev_news.py
  python3 fetch_dev_news.py --no-scrape   # use cached state, just reformat
"""
import json, os, sys, re
from datetime import datetime

import cloudscraper
from anthropic import Anthropic

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from config import SOURCES, ANTHROPIC_API_KEY, CLAUDE_MODEL

DEV_NEWS_JS = os.path.join(os.path.dirname(__file__), '..', '..', 'js', 'dev-news.js')
STATE_PATH  = os.path.join(os.path.dirname(__file__), 'state.json')

SCRIPT_STYLE = re.compile(r"<(script|style)[^>]*>.*?</\1>", re.S | re.I)
BLOCK_BREAK  = re.compile(r"</?(div|p|li|tr|td|th|h[1-6]|br|ul|ol|table)[^>]*>", re.I)
TAG          = re.compile(r"<[^>]+>")

scraper = cloudscraper.create_scraper()


def fetch(url):
    r = scraper.get(url, timeout=25)
    r.raise_for_status()
    return r.text


def extract_text(html):
    text = SCRIPT_STYLE.sub(" ", html)
    text = BLOCK_BREAK.sub("\n", text)
    text = TAG.sub("", text)
    import html as h
    text = h.unescape(text)
    lines = [l.strip() for l in text.splitlines() if l.strip()]
    return "\n".join(lines[:300])


def scrape_all():
    results = []
    for src in SOURCES:
        name, url = src["name"], src["url"]
        print(f"  Fetching {name}...")
        try:
            html = fetch(url)
            text = extract_text(html)
            results.append(f"=== {name} ===\n{text[:4000]}")
        except Exception as e:
            print(f"    Could not reach: {e}")
    return "\n\n".join(results)


def ask_claude(raw_text):
    client = Anthropic(api_key=ANTHROPIC_API_KEY)
    prompt = f"""You write the Development News section for a monthly commercial real estate investor newsletter for Kevin Andreson at Keller Williams Realty Black Hills, Rapid City SD.

From the planning/zoning page content below, extract the 3-5 most relevant development items for commercial real estate investors in the Black Hills region (Box Elder, Rapid City, Pennington County, Custer, Piedmont). Focus on: new rezonings, permits, variances, subdivision plats, annexations, large commercial projects, multifamily developments, industrial activity.

Write each item as a single tight sentence — specific address or parcel if available, what's happening, why it matters to an investor. Investor tone, no fluff.

Format as a JSON array of strings, e.g.:
["Item one text.", "Item two text.", "Item three text."]

If there are no relevant items, return an empty array: []

Planning page content:
{raw_text[:18000]}"""

    msg = client.messages.create(
        model=CLAUDE_MODEL,
        max_tokens=800,
        messages=[{"role": "user", "content": prompt}]
    )
    raw = msg.content[0].text.strip()
    match = re.search(r'\[[\s\S]*\]', raw)
    if match:
        return json.loads(match.group())
    return []


def write_dev_news(items):
    payload = {
        "generated": datetime.now().strftime("%B %d, %Y"),
        "items": items,
    }
    content = (
        f"// Auto-generated by fetch_dev_news.py — {payload['generated']}\n"
        f"window.DEV_NEWS = {json.dumps(payload, indent=2)};\n"
    )
    os.makedirs(os.path.dirname(DEV_NEWS_JS), exist_ok=True)
    with open(DEV_NEWS_JS, 'w') as f:
        f.write(content)
    print(f"✓ Wrote {len(items)} item(s) to dev-news.js")


def main():
    no_scrape = "--no-scrape" in sys.argv

    print("\nDevelopment News Fetcher")
    print("=" * 40)

    if no_scrape and os.path.exists(STATE_PATH):
        print("Using cached zoning monitor state...")
        with open(STATE_PATH) as f:
            state = json.load(f)
        raw_text = "\n\n".join(
            f"=== {url} ===\n" + "\n".join(v.get("lines", [])[:200])
            for url, v in state.items()
        )
    else:
        print("Scraping planning sources...")
        raw_text = scrape_all()

    if not raw_text.strip():
        print("Nothing scraped — writing empty dev-news.js")
        write_dev_news([])
        return

    print("Asking Claude to format newsletter bullets...")
    items = ask_claude(raw_text)

    if items:
        print("\nDevelopment news items:")
        for item in items:
            print(f"  · {item}")
    else:
        print("No relevant development items found this run.")

    write_dev_news(items)


if __name__ == "__main__":
    main()
